In [423]:
import pandas as pd
import json
jsn = {
"vendordata": 
[
    {
        "tokenid": 123456789,
        "lifnr": "3112415",
        "land1": "in",
        "name1": "maruti fiber com",
        "name2": "",
        "name3": "d-305, 4rth fl, kh no-128,",
        "name4": "indra park, najafgarh",
        "ort01": "new delhi",
        "pstlz": 110043,
        "regio": "dl",
        "stras": "",
        "adrnr": 46832,
        "telf1": "91 9212094197",
        "telf2": 25084601,
        "city1": "new delhi",
        "add1": "d-305, 4rth fl, kh no-128,",
        "add2": "indra park, najafgarh",
        "zzgstno": "07abnps0586r1zm",
        "j_1ipanno": "abnps1586r",
        "upload_date": "01/12/2021",
        "bankdetails": [
            {
                "buzei": 1,
                "bankn": "11271511111176",
                "bankl": "ucba0001027",
                "banks": "in"
            },
            {
                "buzei": 2,
                "bankn": "11271511111333",
                "bankl": "ucba0001028",
                "banks": "in"
            }
        ],
        "withholding": [
            {
                "buzei": 1,
                "witht": "ci",
                "wt_withcd": "02"
            },
            {
                "buzei": 2,
                "witht": "ci",
                "wt_withcd": "03"
            }
        ]   
    },
    {
        "tokenid": 123456789,
        "lifnr": "3112416",
        "land1": "in",
        "name1": "maruti fiber com",
        "name2": "",
        "name3": "d-305, 4rth fl, kh no-128,",
        "name4": "indra park, najafgarh",
        "ort01": "new delhi",
        "pstlz": 110043,
        "regio": "dl",
        "stras": "",
        "adrnr": 46832,
        "telf1": "91 9212094197",
        "telf2": 25084601,
        "city1": "new delhi",
        "add1": "d-305, 4rth fl, kh no-128,",
        "add2": "indra park, najafgarh",
        "zzgstno": "07abnps0586r1zm",
        "j_1ipanno": "abnps1586r",
        "upload_date": "01/12/2021",
        "bankdetails": [{
                "buzei": 1,
                "bankn": "11271511111176",
                "bankl": "ucba0001027",
                "banks": "in"
            },
            {
                "buzei": 2,
                "bankn": "11271511111333",
                "bankl": "ucba0001028",
                "banks": "in"
            }
        ]   
    },
    {
        "tokenid": 123456789,
        "lifnr": "3112417",
        "land1": "in",
        "name1": "Datsun fiber com",
        "name2": "",
        "name3": "d-305, 4rth fl, kh no-128,",
        "name4": "indra park, najafgarh",
        "ort01": "new delhi",
        "pstlz": 110043,
        "regio": "dl",
        "stras": "",
        "adrnr": 46832,
        "telf1": "91 9212094197",
        "telf2": 25084601,
        "city1": "new delhi",
        "add1": "d-305, 4rth fl, kh no-128,",
        "add2": "indra park, najafgarh",
        "zzgstno": "07abnps0586r1zm",
        "j_1ipanno": "abnps1586r",
        "upload_date": "01/12/2021",
    },
    {
        "tokenid": 123456789,
        "lifnr": "3112422",
        "land1": "in",
        "name1": "merc fiber com",
        "name2": "",
        "name3": "d-305, 4rth fl, kh no-128,",
        "name4": "indra park, najafgarh",
        "ort01": "new delhi",
        "pstlz": 110043,
        "regio": "dl",
        "stras": "",
        "adrnr": 46832,
        "telf1": "91 9212094197",
        "telf2": 25084601,
        "city1": "new delhi",
        "add1": "d-305, 4rth fl, kh no-128,",
        "add2": "indra park, najafgarh",
        "zzgstno": "07abnps0586r1zm",
        "j_1ipanno": "abnps1586r",
        "upload_date": "01/12/2021",
        "bankdetails": [
            {
                "buzei": 1,
                "bankn": "11271511111176",
                "bankl": "ucba0001027",
                "banks": "in"
            }
        ],
        "withholding": [
            {
                "buzei": 1,
                "witht": "ci",
                "wt_withcd": "02"
            }
        ]   
    },
    {
        "tokenid": 123456789,
        "lifnr": "3112444",
        "land1": "in",
        "name1": "bmw fiber com",
        "name2": "",
        "name3": "d-305, 4rth fl, kh no-128,",
        "name4": "indra park, najafgarh",
        "ort01": "new delhi",
        "pstlz": 110043,
        "regio": "dl",
        "stras": "",
        "adrnr": 46832,
        "telf1": "91 9212094197",
        "telf2": 25084601,
        "city1": "new delhi",
        "add1": "d-305, 4rth fl, kh no-128,",
        "add2": "indra park, najafgarh",
        "zzgstno": "07abnps0586r1zm",
        "j_1ipanno": "abnps1586r",
        "upload_date": "01/12/2021",
        "withholding": [
            {
                "buzei": 1,
                "witht": "ci",
                "wt_withcd": "02"
            }
        ]   
    }   
]
}
print(jsn)
print (len(jsn))

{'vendordata': [{'tokenid': 123456789, 'lifnr': '3112415', 'land1': 'in', 'name1': 'maruti fiber com', 'name2': '', 'name3': 'd-305, 4rth fl, kh no-128,', 'name4': 'indra park, najafgarh', 'ort01': 'new delhi', 'pstlz': 110043, 'regio': 'dl', 'stras': '', 'adrnr': 46832, 'telf1': '91 9212094197', 'telf2': 25084601, 'city1': 'new delhi', 'add1': 'd-305, 4rth fl, kh no-128,', 'add2': 'indra park, najafgarh', 'zzgstno': '07abnps0586r1zm', 'j_1ipanno': 'abnps1586r', 'upload_date': '01/12/2021', 'bankdetails': [{'buzei': 1, 'bankn': '11271511111176', 'bankl': 'ucba0001027', 'banks': 'in'}, {'buzei': 2, 'bankn': '11271511111333', 'bankl': 'ucba0001028', 'banks': 'in'}], 'withholding': [{'buzei': 1, 'witht': 'ci', 'wt_withcd': '02'}, {'buzei': 2, 'witht': 'ci', 'wt_withcd': '03'}]}, {'tokenid': 123456789, 'lifnr': '3112416', 'land1': 'in', 'name1': 'maruti fiber com', 'name2': '', 'name3': 'd-305, 4rth fl, kh no-128,', 'name4': 'indra park, najafgarh', 'ort01': 'new delhi', 'pstlz': 110043, 'regio': 'dl', 'stras': '', 'adrnr': 46832, 'telf1': '91 9212094197', 'telf2': 25084601, 'city1': 'new delhi', 'add1': 'd-305, 4rth fl, kh no-128,', 'add2': 'indra park, najafgarh', 'zzgstno': '07abnps0586r1zm', 'j_1ipanno': 'abnps1586r', 'upload_date': '01/12/2021', 'bankdetails': [{'buzei': 1, 'bankn': '11271511111176', 'bankl': 'ucba0001027', 'banks': 'in'}, {'buzei': 2, 'bankn': '11271511111333', 'bankl': 'ucba0001028', 'banks': 'in'}]}, {'tokenid': 123456789, 'lifnr': '3112417', 'land1': 'in', 'name1': 'Datsun fiber com', 'name2': '', 'name3': 'd-305, 4rth fl, kh no-128,', 'name4': 'indra park, najafgarh', 'ort01': 'new delhi', 'pstlz': 110043, 'regio': 'dl', 'stras': '', 'adrnr': 46832, 'telf1': '91 9212094197', 'telf2': 25084601, 'city1': 'new delhi', 'add1': 'd-305, 4rth fl, kh no-128,', 'add2': 'indra park, najafgarh', 'zzgstno': '07abnps0586r1zm', 'j_1ipanno': 'abnps1586r', 'upload_date': '01/12/2021'}, {'tokenid': 123456789, 'lifnr': '3112422', 'land1': 'in', 'name1': 'merc fiber com', 'name2': '', 'name3': 'd-305, 4rth fl, kh no-128,', 'name4': 'indra park, najafgarh', 'ort01': 'new delhi', 'pstlz': 110043, 'regio': 'dl', 'stras': '', 'adrnr': 46832, 'telf1': '91 9212094197', 'telf2': 25084601, 'city1': 'new delhi', 'add1': 'd-305, 4rth fl, kh no-128,', 'add2': 'indra park, najafgarh', 'zzgstno': '07abnps0586r1zm', 'j_1ipanno': 'abnps1586r', 'upload_date': '01/12/2021', 'bankdetails': [{'buzei': 1, 'bankn': '11271511111176', 'bankl': 'ucba0001027', 'banks': 'in'}], 'withholding': [{'buzei': 1, 'witht': 'ci', 'wt_withcd': '02'}]}, {'tokenid': 123456789, 'lifnr': '3112444', 'land1': 'in', 'name1': 'bmw fiber com', 'name2': '', 'name3': 'd-305, 4rth fl, kh no-128,', 'name4': 'indra park, najafgarh', 'ort01': 'new delhi', 'pstlz': 110043, 'regio': 'dl', 'stras': '', 'adrnr': 46832, 'telf1': '91 9212094197', 'telf2': 25084601, 'city1': 'new delhi', 'add1': 'd-305, 4rth fl, kh no-128,', 'add2': 'indra park, najafgarh', 'zzgstno': '07abnps0586r1zm', 'j_1ipanno': 'abnps1586r', 'upload_date': '01/12/2021', 'withholding': [{'buzei': 1, 'witht': 'ci', 'wt_withcd': '02'}]}]}
1

In [424]:
data1=jsn["vendordata"]
print(len(data1))

5

In [430]:
df_final1=pd.DataFrame()
df_final2=pd.DataFrame()
df_final3=pd.DataFrame()
df_final4=pd.DataFrame()
df_final=pd.DataFrame()
for i in range(len(data1)):
 
    result3 = pd.json_normalize(
    data1[i],errors='ignore')
    try:
        result = pd.json_normalize(
        data1[i], ["bankdetails"], ["tokenid","lifnr", "name1"],errors='ignore')
       
        
        
       
    except KeyError as ke:
         print('Key Not Found in Employee Dictionary:', ke)
    
    
    try:
        result2=   pd.json_normalize(
        data1[i], ["withholding"],["tokenid","lifnr", "name1"])
    except KeyError as kf:
        print('Key Not Found in Employee Dictionary:', kf)
        

    df_final1=df_final1.append(result2)
    df_final2=df_final2.append(result)
    df_final3=df_final3.append(result3)


df_final3.drop('withholding', inplace=True, axis=1)
df_final3.drop('bankdetails', inplace=True, axis=1)
df_final4=df_final2.merge(df_final1, on=['tokenid','buzei','name1'], how='right')
df_final4 = df_final4.rename(columns={'lifnr_y': 'lifnr'})
df_final4.drop_duplicates()
df_final=df_final3.merge(df_final4, on=['tokenid','lifnr','name1'], how='left')
df_final.drop('lifnr_x', inplace=True, axis=1)
df_final.drop_duplicates()

Key Not Found in Employee Dictionary: 'withholding'
Key Not Found in Employee Dictionary: 'bankdetails'
Key Not Found in Employee Dictionary: 'withholding'
Key Not Found in Employee Dictionary: 'bankdetails'

,tokenid,lifnr,land1,name1,name2,name3,name4,ort01,pstlz,regio,...,add2,zzgstno,j_1ipanno,upload_date,buzei,bankn,bankl,banks,witht,wt_withcd
0,123456789,3112415,in,maruti fiber com,,"d-305, 4rth fl, kh no-128,","indra park, najafgarh",new delhi,110043,dl,...,"indra park, najafgarh",07abnps0586r1zm,abnps1586r,01/12/2021,1.0,11271511111176,ucba0001027,in,ci,02
3,123456789,3112415,in,maruti fiber com,,"d-305, 4rth fl, kh no-128,","indra park, najafgarh",new delhi,110043,dl,...,"indra park, najafgarh",07abnps0586r1zm,abnps1586r,01/12/2021,2.0,11271511111333,ucba0001028,in,ci,03
18,123456789,3112416,in,maruti fiber com,,"d-305, 4rth fl, kh no-128,","indra park, najafgarh",new delhi,110043,dl,...,"indra park, najafgarh",07abnps0586r1zm,abnps1586r,01/12/2021,NaN,NaN,NaN,NaN,NaN,NaN
19,123456789,3112417,in,Datsun fiber com,,"d-305, 4rth fl, kh no-128,","indra park, najafgarh",new delhi,110043,dl,...,"indra park, najafgarh",07abnps0586r1zm,abnps1586r,01/12/2021,NaN,NaN,NaN,NaN,NaN,NaN
20,123456789,3112422,in,merc fiber com,,"d-305, 4rth fl, kh no-128,","indra park, najafgarh",new delhi,110043,dl,...,"indra park, najafgarh",07abnps0586r1zm,abnps1586r,01/12/2021,1.0,11271511111176,ucba0001027,in,ci,02
22,123456789,3112444,in,bmw fiber com,,"d-305, 4rth fl, kh no-128,","indra park, najafgarh",new delhi,110043,dl,...,"indra park, najafgarh",07abnps0586r1zm,abnps1586r,01/12/2021,1.0,NaN,NaN,NaN,ci,02

In [265]:
for i in  data:
    print(i['toke'])
   


#print(result2)
#print(result)

KeyError: 'bankdetails'

In [203]:
df=pd.json_normalize(data,"bankdetails")
df

KeyError: 'bankdetails'

In [201]:
#FIELDS = ["vendordata.tokenid", "vendordata.bankdetails.buzei", "vendordata.withholding.witht"]
FIELDS = ["tokenid","vendordata.bankdetails.buzei"]
flat_list = [item for sublist in jsn['vendordata']for item in sublist['bankdetails']]
df=pd.json_normalize(flat_list,"vendordata",record_path=["bankdetails","buzei","bankn","bankl","banks"],errors='ignore')
df

KeyError: 'bankdetails'

In [180]:
data = [
    {
        "state": "Florida",
        "shortname": "FL",
        "info": {"governor": "Rick Scott"},
        "counties": [
            {"name": "Dade", "population": 12345},
            {"name": "Broward", "population": 40000},
            {"name": "Palm Beach", "population": 60000},
        ],
    },
    {
        "state": "Ohio",
        "shortname": "OH",
        "info": {"governor": "John Kasich"},
        "counties": [
            {"name": "Summit", "population": 1234},
            {"name": "Cuyahoga", "population": 1337},
        ],
    },
]
result = pd.json_normalize(
    data, "counties", ["state", "shortname", ["info", "governor"]])
result

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich